version: "3.7"

services:
  redis:
    image: "redis"
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3
    ports:
      - 4369:4369
      - 5671:5671
      - 5672:5672
      - 15672:15672

  flower:
    image: mher/flower
    environment:
      - CELERY_BROKER_URL=amqp://rabbitmq//
      - FLOWER_PORT=8888
    ports:
      - 8888:8888

  worker:
    hostname: worker
    build: .
    depends_on:
      - rabbitmq
      - redis
    volumes:
      - "./:/app"
    command: "celery -A celery_worker.celery worker --loglevel=INFO"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  api:
    build: .
    hostname: api
    depends_on:
      - rabbitmq
      - redis
    volumes:
      - "./:/app"
    command: "uvicorn main:app --reload"
